language: python
python:
  - "2.7"

os:
  - linux

env:                                                                           
  - PYCOIN_NATIVE=openssl

install:
  - pip install cython
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install

script:
  - bash test.sh

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
